### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference

### ISSUE THREAD

**Issue by Steven-Yao** [hypertrack/smart-scheduler-android#10]
Hi guys, my app got this crash on many Android 5.1.1(Lollipop) devices. It looks like a platform bug, and I can do nothing, is there any solutions to solve this issue？

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference
	at android.os.Parcel.readException(Parcel.java:1552)
	at android.os.Parcel.readException(Parcel.java:1499)
	at android.app.job.IJobCallback$Stub$Proxy.jobFinished(IJobCallback.java:167)
	at android.app.job.JobService$JobHandler.handleMessage(JobService.java:147)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5359)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)

**Comment by robelgado** [comment]
Seeing the same issue, on the same version....

**Comment by shwethag** [comment]
+1 Seeing mostly in 5.1 devices and some 6.0 device

**Comment by lucky1412** [comment]
java.lang.NullPointerException:
at android.os.Parcel.readException (Parcel.java:1546)
at android.os.Parcel.readException (Parcel.java:1493)
at android.app.job.IJobCallback$Stub$Proxy.jobFinished (IJobCallback.java:167)
at android.app.job.JobService$JobHandler.handleMessage (JobService.java:147)
at android.os.Handler.dispatchMessage (Handler.java:102)
at android.os.Looper.loop (Looper.java:145)
at android.app.ActivityThread.main (ActivityThread.java:5942)
at java.lang.reflect.Method.invoke (Native Method)
at java.lang.reflect.Method.invoke (Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1400)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1195)
Android 5.1
115
53.0%
Android 5.0
60
27.6%
Android 6.0
42
19.4%
