### ISSUE TITLE
NullPointerException jobStatus.getUid()

### ISSUE THREAD

**Issue by NiaNingXue** [hypertrack/smart-scheduler-android#6]
On Samsung 5.1 devices it happens frequently, it maybe the system bug. Do you know how to avoid it?

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.os.Parcel.readException(Parcel.java:1499)
       at android.app.job.IJobCallback$Stub$Proxy.jobFinished(IJobCallback.java:167)
       at android.app.job.JobService$JobHandler.handleMessage(JobService.java:147)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6946)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by NiaNingXue** [comment]
Sorry, I make a mistake.

**Comment by daiwenbo88** [comment]
你好这个问题你是怎么解决的,可以说明吗 我也遇到了

**Comment by NiaNingXue** [comment]
至今没解决，系统bug没办法。。。。。

**Comment by jeryfer** [comment]
请问如何规避这个问题呢？

**Comment by jeryfer** [comment]
我提了个问题，也没有完美的解决办法[http://stackoverflow.com/questions/41531529/attempt-to-invoke-virtual-method-on-a-null-object-reference-int-com-android-ser](http://stackoverflow.com/questions/41531529/attempt-to-invoke-virtual-method-on-a-null-object-reference-int-com-android-ser)
